import {
  type ProcedureDefinition,
  type ComplicationType,
  type DecisionArchetypeType,
  type Vitals,
  type PatientStateTemplate,
  type RiskProfile,
  type EscalationModel,
  COMPLICATION_TYPES,
} from "../state/models.js";

// ── Helper to build escalation curve from total ticks ──
function buildEscalation(totalTicks: number, curve: "mild" | "moderate" | "aggressive"): EscalationModel {
  const ratios = {
    mild:      { p1: 0.25, p2: 0.15, p3: 0.25, p4: 0.20, p5: 0.15 },
    moderate:  { p1: 0.20, p2: 0.15, p3: 0.25, p4: 0.25, p5: 0.15 },
    aggressive:{ p1: 0.12, p2: 0.13, p3: 0.25, p4: 0.30, p5: 0.20 },
  }[curve];

  const r = (pct: number) => Math.round(totalTicks * pct);
  const t = (start: number, end: number): [number, number] => [
    Math.max(1, start),
    Math.min(totalTicks, end),
  ];

  let cursor = 0;
  const p1e = cursor + r(ratios.p1); cursor = p1e;
  const p2e = cursor + r(ratios.p2); cursor = p2e;
  const p3e = cursor + r(ratios.p3); cursor = p3e;
  const p4e = cursor + r(ratios.p4); cursor = p4e;

  return {
    phase1: { tickRange: t(1, p1e),                                  label: "Stable Workup" },
    phase2: { tickRange: t(p1e + 1, p2e),                             label: "Complication Risk" },
    phase3: { tickRange: t(p2e + 1, p3e),                             label: "Active Complication" },
    phase4: { tickRange: t(p3e + 1, p4e),                             label: "Crisis Management" },
    phase5: { tickRange: t(p4e + 1, totalTicks),                      label: "Recovery / Failure" },
  };
}

// ── Shorthand complication weight builder ──
function cw(weights: [ComplicationType, number][]): Record<ComplicationType, number> {
  const result: Record<string, number> = {};
  for (const [k, v] of weights) result[k] = v;
  return result as Record<ComplicationType, number>;
}

// ── Risk profile presets ──
const RISK_PROFILES: Record<string, RiskProfile> = {
  low:       { base_complication_chance: 0.15, crisis_threshold_factor: 1.5, recovery_speed: 0.8 },
  moderate:  { base_complication_chance: 0.25, crisis_threshold_factor: 1.0, recovery_speed: 0.5 },
  high:      { base_complication_chance: 0.35, crisis_threshold_factor: 0.7, recovery_speed: 0.3 },
  critical:  { base_complication_chance: 0.45, crisis_threshold_factor: 0.5, recovery_speed: 0.2 },
};

// ════════════════════════════════════════════════════
//  ALL 30 PROCEDURES
// ════════════════════════════════════════════════════

const ALL_30: ProcedureDefinition[] = [

// ── BEGINNER (4) ──
{
  id: "appendectomy",
  name: "Appendectomy",
  category: "beginner",
  specialty: "General Surgery",
  description: "Emergency removal of an inflamed appendix. Watch for perforation and infection.",
  patient: {
    name: "Marcus T.", age: 28, sex: "Male", weight: "95 kg", bloodType: "O+",
    admission: "Acute right lower quadrant pain, rebound tenderness, fever 101.2°F",
    mood: "Anxious", comorbidities: ["obese"],
    baselineVitals: { spo2: 97, heart_rate: 110, bp_systolic: 95, bp_diastolic: 65, temperature: 37.6, respiratory_rate: 22 },
  },
  initialState: {
    vitals_override: { heart_rate: 110, bp_systolic: 95 },
    riskProfile: RISK_PROFILES.moderate,
  },
  complicationWeights: cw([["infection", 5], ["hemorrhage", 2], ["hypoxia", 1]]),
  allowedComplications: ["infection", "hemorrhage", "hypoxia"],
  decisionArchetypes: ["AIRWAY_STABILITY", "BLEEDING_CONTROL", "INFECTION_MANAGEMENT"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op Planning", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision & Access", icon: "🔪", short: "Incision" },
    { id: 4, name: "Core Procedure", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "inguinal-hernia",
  name: "Inguinal Hernia Repair",
  category: "beginner",
  specialty: "General Surgery",
  description: "Elective repair of a reducible inguinal hernia with mesh placement.",
  patient: {
    name: "Michael R.", age: 45, sex: "Male", weight: "82 kg", bloodType: "O+",
    admission: "Right groin bulge for 6 months, fully reducible",
    mood: "Anxious", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: {
    vitals_override: {},
    riskProfile: RISK_PROFILES.low,
  },
  complicationWeights: cw([["hemorrhage", 3], ["nerve_injury", 2], ["infection", 1]]),
  allowedComplications: ["hemorrhage", "nerve_injury", "infection"],
  decisionArchetypes: ["SURGICAL_DECISION", "BLEEDING_CONTROL"],
  escalationCurve: buildEscalation(30, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op Planning", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision & Dissection", icon: "🔪", short: "Dissection" },
    { id: 4, name: "Mesh Placement", icon: "🧱", short: "Mesh" },
    { id: 5, name: "Closure", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "thyroidectomy",
  name: "Thyroidectomy",
  category: "beginner",
  specialty: "ENT",
  description: "Total thyroidectomy for follicular neoplasm. Airway and RLN are critical.",
  patient: {
    name: "Emily R.", age: 38, sex: "Female", weight: "68 kg", bloodType: "A+",
    admission: "Palpable thyroid nodule, Bethesda IV follicular neoplasm",
    mood: "Anxious but well-informed", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: {
    vitals_override: {},
    riskProfile: RISK_PROFILES.low,
  },
  complicationWeights: cw([["hypoxia", 4], ["nerve_injury", 3], ["hemorrhage", 2]]),
  allowedComplications: ["hypoxia", "nerve_injury", "hemorrhage"],
  decisionArchetypes: ["AIRWAY_STABILITY", "DIAGNOSTIC_STEP"],
  escalationCurve: buildEscalation(30, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op Planning", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision & Access", icon: "🔪", short: "Incision" },
    { id: 4, name: "Core Procedure", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "carpal-tunnel-release",
  name: "Carpal Tunnel Release",
  category: "beginner",
  specialty: "Orthopedic",
  description: "Open carpal tunnel release for median nerve decompression at the wrist.",
  patient: {
    name: "Linda K.", age: 52, sex: "Female", weight: "65 kg", bloodType: "B+",
    admission: "Numbness and tingling in thumb, index, and middle fingers for 8 months",
    mood: "Relieved", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: {
    vitals_override: {},
    riskProfile: RISK_PROFILES.low,
  },
  complicationWeights: cw([["nerve_injury", 3], ["infection", 1]]),
  allowedComplications: ["nerve_injury", "infection"],
  decisionArchetypes: ["SURGICAL_DECISION", "PAIN_MANAGEMENT"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Release", icon: "⚕️", short: "Release" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},

// ── INTERMEDIATE (14) ──
{
  id: "cholecystectomy",
  name: "Cholecystectomy",
  category: "intermediate",
  specialty: "General Surgery",
  description: "Laparoscopic removal of gallbladder. Critical view of safety is essential.",
  patient: {
    name: "Sarah J.", age: 42, sex: "Female", weight: "78 kg", bloodType: "B+",
    admission: "Right upper quadrant pain, Murphy's sign positive, history of gallstones",
    mood: "Anxious but cooperative", comorbidities: ["obese"],
    baselineVitals: { spo2: 97, heart_rate: 80, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 80 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["infection", 4], ["hemorrhage", 3], ["hypoxia", 2]]),
  allowedComplications: ["infection", "hemorrhage", "hypoxia"],
  decisionArchetypes: ["INFECTION_MANAGEMENT", "DIAGNOSTIC_STEP"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Evaluation", icon: "🩺", short: "Intake" },
    { id: 2, name: "Stabilization", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Laparoscopic Entry", icon: "🔪", short: "Access" },
    { id: 4, name: "Gallbladder Removal", icon: "⚕️", short: "Removal" },
    { id: 5, name: "Hemostasis & Closure", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op Debrief", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 35,
},
{
  id: "acl-reconstruction",
  name: "ACL Reconstruction",
  category: "intermediate",
  specialty: "Orthopedic",
  description: "Arthroscopic anterior cruciate ligament reconstruction with graft fixation.",
  patient: {
    name: "Marcus T.", age: 22, sex: "Male", weight: "82 kg", bloodType: "O+",
    admission: "Knee injury during soccer, positive Lachman test",
    mood: "Determined", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 3], ["nerve_injury", 2], ["infection", 2]]),
  allowedComplications: ["hemorrhage", "nerve_injury", "infection"],
  decisionArchetypes: ["SURGICAL_DECISION", "PAIN_MANAGEMENT"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Evaluation", icon: "🦵", short: "Exam" },
    { id: 2, name: "Access", icon: "🎥", short: "Arthroscopy" },
    { id: 3, name: "Graft Harvesting", icon: "✂️", short: "Graft" },
    { id: 4, name: "Tunnel Drilling", icon: "⚙️", short: "Drilling" },
    { id: 5, name: "Fixation", icon: "🔩", short: "Fixation" },
    { id: 6, name: "Recovery", icon: "🏆", short: "Rehab" },
  ],
  totalTicks: 30,
},
{
  id: "c-section",
  name: "Cesarean Section",
  category: "intermediate",
  specialty: "OB/GYN",
  description: "Emergency cesarean delivery for non-reassuring fetal tracing. Dual patient focus.",
  patient: {
    name: "Maria L.", age: 31, sex: "Female", weight: "92 kg", bloodType: "A+",
    admission: "39 weeks gestation, failure to progress, non-reassuring fetal tracing",
    mood: "Exhausted but determined", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 88, bp_systolic: 125, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 18 },
  },
  initialState: { vitals_override: { heart_rate: 88, bp_systolic: 125, respiratory_rate: 18 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 5], ["hypoxia", 3], ["cardiac_arrhythmia", 2]]),
  allowedComplications: ["hemorrhage", "hypoxia", "cardiac_arrhythmia"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL", "AIRWAY_STABILITY"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Evaluation", icon: "🤰", short: "Labor" },
    { id: 2, name: "Intake", icon: "💉", short: "Epidural" },
    { id: 3, name: "Abdominal Entry", icon: "⚗️", short: "Pfannenstiel" },
    { id: 4, name: "Delivery", icon: "👶", short: "Delivery" },
    { id: 5, name: "Closure", icon: "🪡", short: "Repair" },
    { id: 6, name: "Post-Partum", icon: "👩‍🍼", short: "Recovery" },
  ],
  totalTicks: 30,
},
{
  id: "total-knee-replacement",
  name: "Total Knee Replacement",
  category: "intermediate",
  specialty: "Orthopedic",
  description: "Total knee arthroplasty for severe osteoarthritis with cemented components.",
  patient: {
    name: "Evelyn W.", age: 68, sex: "Female", weight: "74 kg", bloodType: "A-",
    admission: "Severe right knee osteoarthritis, bone-on-bone medial joint space",
    mood: "Determined to walk again", comorbidities: ["hypertension", "diabetes"],
    baselineVitals: { spo2: 97, heart_rate: 82, bp_systolic: 155, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 82, bp_systolic: 155 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["thrombosis", 5], ["infection", 3], ["nerve_injury", 2]]),
  allowedComplications: ["thrombosis", "infection", "nerve_injury"],
  decisionArchetypes: ["PAIN_MANAGEMENT", "POST_OP_MONITORING"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Consultation", icon: "📐", short: "Template" },
    { id: 2, name: "Approach", icon: "🔪", short: "Entry" },
    { id: 3, name: "Osteotomy", icon: "🪚", short: "Cuts" },
    { id: 4, name: "Trialing", icon: "👟", short: "Sizing" },
    { id: 5, name: "Fixation", icon: "🧱", short: "Cement" },
    { id: 6, name: "Closure", icon: "🪡", short: "Closing" },
  ],
  totalTicks: 35,
},
{
  id: "total-hysterectomy",
  name: "Total Hysterectomy",
  category: "intermediate",
  specialty: "OB/GYN",
  description: "Total abdominal hysterectomy for fibroids. Ureter and vessel identification critical.",
  patient: {
    name: "Patricia M.", age: 46, sex: "Female", weight: "75 kg", bloodType: "AB+",
    admission: "Large uterine fibroids causing menorrhagia and anemia",
    mood: "Ready", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 80, bp_systolic: 118, bp_diastolic: 75, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 5], ["infection", 3], ["nerve_injury", 2]]),
  allowedComplications: ["hemorrhage", "infection", "nerve_injury"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL", "INFECTION_MANAGEMENT"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Hysterectomy", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "sigmoid-colectomy",
  name: "Sigmoid Colectomy",
  category: "intermediate",
  specialty: "General Surgery",
  description: "Laparoscopic sigmoid colectomy for diverticulitis with abscess. Leak test is critical.",
  patient: {
    name: "Robert J.", age: 58, sex: "Male", weight: "88 kg", bloodType: "A+",
    admission: "Left lower quadrant pain, fever, CT showing sigmoid diverticulitis with abscess",
    mood: "Concerned", comorbidities: ["hypertension", "diabetes"],
    baselineVitals: { spo2: 97, heart_rate: 76, bp_systolic: 140, bp_diastolic: 80, temperature: 37.5, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 76, bp_systolic: 140, temperature: 37.5 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["infection", 5], ["hemorrhage", 2], ["nerve_injury", 1]]),
  allowedComplications: ["infection", "hemorrhage", "nerve_injury"],
  decisionArchetypes: ["INFECTION_MANAGEMENT", "DIAGNOSTIC_STEP"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op Planning", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision & Access", icon: "🔪", short: "Incision" },
    { id: 4, name: "Core Procedure", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "lap-cholecystectomy",
  name: "Laparoscopic Cholecystectomy",
  category: "intermediate",
  specialty: "Laparoscopic",
  description: "Laparoscopic cholecystectomy emphasizing critical view of safety. Bile duct injury risk.",
  patient: {
    name: "Sarah J.", age: 42, sex: "Female", weight: "78 kg", bloodType: "B+",
    admission: "Right upper quadrant pain, Murphy's sign positive, gallstones",
    mood: "Anxious but cooperative", comorbidities: ["obese"],
    baselineVitals: { spo2: 97, heart_rate: 80, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 80 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 3], ["infection", 2], ["nerve_injury", 2]]),
  allowedComplications: ["hemorrhage", "infection", "nerve_injury"],
  decisionArchetypes: ["DIAGNOSTIC_STEP", "SURGICAL_DECISION"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Evaluation", icon: "🩺", short: "Intake" },
    { id: 2, name: "Stabilization", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Laparoscopic Entry", icon: "🔪", short: "Access" },
    { id: 4, name: "Gallbladder Removal", icon: "⚕️", short: "Removal" },
    { id: 5, name: "Hemostasis & Closure", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op Debrief", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 35,
},
{
  id: "radical-nephrectomy",
  name: "Radical Nephrectomy",
  category: "intermediate",
  specialty: "Urology",
  description: "Radical nephrectomy for renal cell carcinoma. Vascular control is paramount.",
  patient: {
    name: "James H.", age: 58, sex: "Male", weight: "90 kg", bloodType: "O-",
    admission: "Right renal mass on imaging, hematuria, weight loss",
    mood: "Stoic", comorbidities: ["hypertension"],
    baselineVitals: { spo2: 97, heart_rate: 78, bp_systolic: 145, bp_diastolic: 90, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { bp_systolic: 145 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 6], ["cardiac_arrhythmia", 2], ["infection", 2]]),
  allowedComplications: ["hemorrhage", "cardiac_arrhythmia", "infection"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Nephrectomy", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 35,
},
{
  id: "hip-replacement",
  name: "Total Hip Replacement",
  category: "intermediate",
  specialty: "Orthopedic",
  description: "Total hip arthroplasty for osteoarthritis. Fat embolism and dislocation are key risks.",
  patient: {
    name: "Robert J.", age: 68, sex: "Male", weight: "82 kg", bloodType: "A+",
    admission: "Right hip osteoarthritis with progressive pain and functional limitation",
    mood: "Hopeful", comorbidities: ["hypertension", "diabetes"],
    baselineVitals: { spo2: 97, heart_rate: 82, bp_systolic: 155, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 82, bp_systolic: 155 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["thrombosis", 4], ["hemorrhage", 3], ["hypoxia", 3], ["nerve_injury", 2]]),
  allowedComplications: ["thrombosis", "hemorrhage", "hypoxia", "nerve_injury"],
  decisionArchetypes: ["POST_OP_MONITORING"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op Planning", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision & Access", icon: "🔪", short: "Incision" },
    { id: 4, name: "Core Procedure", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 35,
},
{
  id: "breast-lumpectomy",
  name: "Breast Lumpectomy",
  category: "intermediate",
  specialty: "Surgical Oncology",
  description: "Breast-conserving surgery for early-stage breast carcinoma with sentinel node biopsy.",
  patient: {
    name: "Diana P.", age: 52, sex: "Female", weight: "62 kg", bloodType: "A+",
    admission: "2cm right breast mass, biopsy-proven invasive ductal carcinoma",
    mood: "Nervous but optimistic", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 76, bp_systolic: 118, bp_diastolic: 78, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.low },
  complicationWeights: cw([["hemorrhage", 3], ["infection", 3]]),
  allowedComplications: ["hemorrhage", "infection"],
  decisionArchetypes: ["INFECTION_MANAGEMENT"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Lumpectomy", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},
{
  id: "tympanoplasty",
  name: "Tympanoplasty",
  category: "intermediate",
  specialty: "ENT",
  description: "Tympanic membrane repair with graft placement. Hearing and facial nerve preservation critical.",
  patient: {
    name: "Ahmed S.", age: 34, sex: "Male", weight: "72 kg", bloodType: "B+",
    admission: "Chronic left ear perforation with conductive hearing loss",
    mood: "Hopeful", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.low },
  complicationWeights: cw([["infection", 4], ["nerve_injury", 3]]),
  allowedComplications: ["infection", "nerve_injury"],
  decisionArchetypes: ["DIAGNOSTIC_STEP"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Approach", icon: "🔪", short: "Approach" },
    { id: 4, name: "Grafting", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},
{
  id: "femoral-nail-fixation",
  name: "Femoral Nail Fixation",
  category: "intermediate",
  specialty: "Orthopedic",
  description: "Intramedullary nailing of femoral shaft fracture. Fat embolism and bleeding are key risks.",
  patient: {
    name: "Tom B.", age: 35, sex: "Male", weight: "85 kg", bloodType: "O+",
    admission: "Right femoral shaft fracture from motorcycle accident",
    mood: "In pain", comorbidities: [],
    baselineVitals: { spo2: 95, heart_rate: 110, bp_systolic: 100, bp_diastolic: 65, temperature: 37.0, respiratory_rate: 22 },
  },
  initialState: { vitals_override: { spo2: 95, heart_rate: 110, bp_systolic: 100, respiratory_rate: 22 }, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["hemorrhage", 5], ["hypoxia", 4], ["fat_embolism" as ComplicationType, 3] as any].filter(x => x) as [ComplicationType, number][]),
  allowedComplications: ["hemorrhage", "hypoxia"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL"],
  escalationCurve: buildEscalation(30, "aggressive"),
  phases: [
    { id: 1, name: "Resuscitation", icon: "🩸", short: "Resus" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Reduction", icon: "🔪", short: "Reduction" },
    { id: 4, name: "Nailing", icon: "⚙️", short: "Nailing" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
},
{
  id: "rotator-cuff-repair",
  name: "Rotator Cuff Repair",
  category: "intermediate",
  specialty: "Orthopedic",
  description: "Arthroscopic rotator cuff repair with suture anchor fixation.",
  patient: {
    name: "Jennifer L.", age: 55, sex: "Female", weight: "68 kg", bloodType: "A+",
    admission: "Right shoulder pain and weakness, MRI showing full-thickness supraspinatus tear",
    mood: "Eager to recover", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 120, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.low },
  complicationWeights: cw([["nerve_injury", 3], ["infection", 2]]),
  allowedComplications: ["nerve_injury", "infection"],
  decisionArchetypes: ["PAIN_MANAGEMENT"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Arthroscopy", icon: "🎥", short: "Scope" },
    { id: 4, name: "Repair", icon: "⚕️", short: "Repair" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},
{
  id: "rhinoplasty",
  name: "Rhinoplasty",
  category: "intermediate",
  specialty: "ENT / Plastic Surgery",
  description: "Open rhinoplasty for nasal deformity. Airway protection during post-op is critical.",
  patient: {
    name: "Sophia W.", age: 27, sex: "Female", weight: "58 kg", bloodType: "AB+",
    admission: "Nasal deformity with breathing difficulty, requesting cosmetic and functional improvement",
    mood: "Nervous", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 115, bp_diastolic: 75, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.low },
  complicationWeights: cw([["hypoxia", 4], ["hemorrhage", 3]]),
  allowedComplications: ["hypoxia", "hemorrhage"],
  decisionArchetypes: ["AIRWAY_STABILITY"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Reshaping", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},
{
  id: "parathyroidectomy",
  name: "Parathyroidectomy",
  category: "intermediate",
  specialty: "ENT / Endocrine",
  description: "Parathyroid adenoma removal. Calcium monitoring and RLN preservation are key.",
  patient: {
    name: "Helen T.", age: 55, sex: "Female", weight: "70 kg", bloodType: "A-",
    admission: "Primary hyperparathyroidism, elevated calcium, parathyroid adenoma on sestamibi",
    mood: "Concerned about calcium", comorbidities: ["hypertension"],
    baselineVitals: { spo2: 98, heart_rate: 78, bp_systolic: 140, bp_diastolic: 85, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { bp_systolic: 140 }, riskProfile: RISK_PROFILES.low },
  complicationWeights: cw([["nerve_injury", 4], ["hemorrhage", 2], ["hypoxia", 2]]),
  allowedComplications: ["nerve_injury", "hemorrhage", "hypoxia"],
  decisionArchetypes: ["DIAGNOSTIC_STEP"],
  escalationCurve: buildEscalation(25, "mild"),
  phases: [
    { id: 1, name: "Patient Intake", icon: "🩺", short: "Intake" },
    { id: 2, name: "Pre-Op", icon: "📋", short: "Pre-Op" },
    { id: 3, name: "Incision", icon: "🔪", short: "Incision" },
    { id: 4, name: "Adenoma Removal", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 25,
},

// ── ADVANCED (12) ──
{
  id: "cabg",
  name: "Heart Bypass (CABG)",
  category: "advanced",
  specialty: "Cardiovascular",
  description: "Coronary artery bypass grafting with cardiopulmonary bypass. Ischemia and arrhythmia are critical.",
  patient: {
    name: "Robert M.", age: 64, sex: "Male", weight: "88 kg", bloodType: "A+",
    admission: "Severe chest pain, multi-vessel coronary artery disease on angiography",
    mood: "Lethargic", comorbidities: ["hypertension", "diabetes"],
    baselineVitals: { spo2: 97, heart_rate: 86, bp_systolic: 163, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 86, bp_systolic: 163 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["cardiac_arrhythmia", 5], ["hemorrhage", 4], ["hypoxia", 3], ["thrombosis", 2]]),
  allowedComplications: ["cardiac_arrhythmia", "hemorrhage", "hypoxia", "thrombosis"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL", "AIRWAY_STABILITY"],
  escalationCurve: buildEscalation(45, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op Evaluation", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Anesthesia & Induction", icon: "💉", short: "Induction" },
    { id: 3, name: "Sternotomy & Harvest", icon: "🔪", short: "Harvest" },
    { id: 4, name: "Cardiopulmonary Bypass", icon: "🫀", short: "CPB" },
    { id: 5, name: "Distal Anastomoses", icon: "🪡", short: "Distal" },
    { id: 6, name: "Proximal & Weaning", icon: "📈", short: "Proximal" },
    { id: 7, name: "Closure", icon: "🪢", short: "Close" },
    { id: 8, name: "ICU & Recovery", icon: "🏥", short: "ICU" },
  ],
  totalTicks: 45,
},
{
  id: "craniotomy",
  name: "Craniotomy",
  category: "advanced",
  specialty: "Neurological",
  description: "Frontal craniotomy for tumor resection. ICP management and neural preservation are paramount.",
  patient: {
    name: "Elena S.", age: 41, sex: "Female", weight: "65 kg", bloodType: "B+",
    admission: "Severe headache, left-sided weakness, 4cm right frontal mass on MRI",
    mood: "Confused", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 78, bp_systolic: 125, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { bp_systolic: 125 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["hemorrhage", 5], ["hypoxia", 3], ["nerve_injury", 4], ["cardiac_arrhythmia", 2]]),
  allowedComplications: ["hemorrhage", "hypoxia", "nerve_injury", "cardiac_arrhythmia"],
  decisionArchetypes: ["DIAGNOSTIC_STEP", "AIRWAY_STABILITY"],
  escalationCurve: buildEscalation(40, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op Evaluation", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Anesthesia & Positioning", icon: "💉", short: "Setup" },
    { id: 3, name: "Incision & Craniotomy", icon: "🔪", short: "Craniotomy" },
    { id: 4, name: "Dural Opening & Exposure", icon: "🧠", short: "Exposure" },
    { id: 5, name: "Tumor Resection", icon: "⚕️", short: "Resection" },
    { id: 6, name: "Closure", icon: "🪡", short: "Closure" },
    { id: 7, name: "Post-Op Care", icon: "🏥", short: "Recovery" },
  ],
  totalTicks: 40,
},
{
  id: "spinal-fusion",
  name: "Spinal Fusion",
  category: "advanced",
  specialty: "Orthopedic / Neurosurgery",
  description: "L4-L5 posterior spinal fusion with pedicle screws and interbody cage. Nerve monitoring critical.",
  patient: {
    name: "David R.", age: 54, sex: "Male", weight: "95 kg", bloodType: "O+",
    admission: "Chronic lower back pain, disc herniation L4-L5, failed conservative treatment",
    mood: "Hopeful but cautious", comorbidities: ["hypertension"],
    baselineVitals: { spo2: 98, heart_rate: 72, bp_systolic: 140, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { bp_systolic: 140 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["nerve_injury", 5], ["hemorrhage", 4], ["infection", 3], ["thrombosis", 2]]),
  allowedComplications: ["nerve_injury", "hemorrhage", "infection", "thrombosis"],
  decisionArchetypes: ["SURGICAL_DECISION"],
  escalationCurve: buildEscalation(40, "aggressive"),
  phases: [
    { id: 1, name: "Consultation", icon: "🧠", short: "Neuro Exam" },
    { id: 2, name: "Positioning", icon: "🛌", short: "Prone" },
    { id: 3, name: "Exposure", icon: "⚒️", short: "Incision" },
    { id: 4, name: "Decompression", icon: "🔬", short: "Laminectomy" },
    { id: 5, name: "Fusion", icon: "🔩", short: "Screw/Cage" },
    { id: 6, name: "Verification", icon: "📸", short: "Final X-ray" },
  ],
  totalTicks: 40,
},
{
  id: "exploratory-laparotomy",
  name: "Exploratory Laparotomy",
  category: "advanced",
  specialty: "Trauma Surgery",
  description: "Emergent trauma laparotomy for penetrating injury. Damage control and hemorrhage control.",
  patient: {
    name: "Marcus Doe", age: 28, sex: "Male", weight: "85 kg", bloodType: "O-",
    admission: "Gunshot wound to RUQ, hypotensive shock (85/50), tachycardic (135)",
    mood: "Agitated/Obtunded", comorbidities: [],
    baselineVitals: { spo2: 92, heart_rate: 130, bp_systolic: 85, bp_diastolic: 55, temperature: 36.5, respiratory_rate: 24 },
  },
  initialState: { vitals_override: { spo2: 92, heart_rate: 130, bp_systolic: 85, bp_diastolic: 55, respiratory_rate: 24, temperature: 36.5 }, riskProfile: RISK_PROFILES.critical },
  complicationWeights: cw([["hemorrhage", 8], ["cardiac_arrhythmia", 3], ["infection", 3], ["hypoxia", 2]]),
  allowedComplications: ["hemorrhage", "cardiac_arrhythmia", "infection", "hypoxia"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL", "INFECTION_MANAGEMENT"],
  escalationCurve: buildEscalation(35, "aggressive"),
  phases: [
    { id: 1, name: "Resuscitation", icon: "🩸", short: "MTP/FAST" },
    { id: 2, name: "Control", icon: "🔪", short: "Laparotomy" },
    { id: 3, name: "Systematic Review", icon: "🔍", short: "Audit" },
    { id: 4, name: "Intervention", icon: "✂️", short: "Repair" },
    { id: 5, name: "Damage Control", icon: "🩹", short: "Packing" },
    { id: 6, name: "Stabilization", icon: "🚑", short: "ICU Handoff" },
  ],
  totalTicks: 35,
},
{
  id: "pulmonary-lobectomy",
  name: "Pulmonary Lobectomy",
  category: "advanced",
  specialty: "Thoracic",
  description: "Video-assisted thoracoscopic lobectomy for lung cancer. Air leak and respiratory failure are key risks.",
  patient: {
    name: "William C.", age: 62, sex: "Male", weight: "80 kg", bloodType: "B-",
    admission: "2.5cm right upper lobe mass, biopsy-proven adenocarcinoma",
    mood: "Resigned", comorbidities: ["copd"],
    baselineVitals: { spo2: 94, heart_rate: 82, bp_systolic: 135, bp_diastolic: 85, temperature: 37.0, respiratory_rate: 20 },
  },
  initialState: { vitals_override: { spo2: 94, respiratory_rate: 20 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["hypoxia", 6], ["hemorrhage", 3], ["cardiac_arrhythmia", 3], ["infection", 2]]),
  allowedComplications: ["hypoxia", "hemorrhage", "cardiac_arrhythmia", "infection"],
  decisionArchetypes: ["AIRWAY_STABILITY"],
  escalationCurve: buildEscalation(40, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Positioning", icon: "🛌", short: "Lateral" },
    { id: 3, name: "VATS Access", icon: "🔪", short: "Access" },
    { id: 4, name: "Lobectomy", icon: "⚕️", short: "Resection" },
    { id: 5, name: "Closure", icon: "🪡", short: "Closing" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 40,
},
{
  id: "whipple",
  name: "Whipple Procedure",
  category: "advanced",
  specialty: "Surgical Oncology",
  description: "Pancreaticoduodenectomy for pancreatic head mass. Massive complication risk across all systems.",
  patient: {
    name: "Harold F.", age: 67, sex: "Male", weight: "78 kg", bloodType: "A+",
    admission: "Pancreatic head mass with jaundice, weight loss, and elevated CA 19-9",
    mood: "Somber", comorbidities: ["diabetes", "hypertension"],
    baselineVitals: { spo2: 97, heart_rate: 86, bp_systolic: 155, bp_diastolic: 85, temperature: 37.2, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { heart_rate: 86, bp_systolic: 155, temperature: 37.2 }, riskProfile: RISK_PROFILES.critical },
  complicationWeights: cw([["infection", 6], ["hemorrhage", 5], ["cardiac_arrhythmia", 3], ["hypoxia", 3], ["thrombosis", 2]]),
  allowedComplications: ["infection", "hemorrhage", "cardiac_arrhythmia", "hypoxia", "thrombosis"],
  decisionArchetypes: ["INFECTION_MANAGEMENT", "HEMODYNAMIC_CONTROL"],
  escalationCurve: buildEscalation(50, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Exploration", icon: "🔍", short: "Explore" },
    { id: 3, name: "Resection", icon: "🔪", short: "Resect" },
    { id: 4, name: "Reconstruction", icon: "🪡", short: "Reconstruct" },
    { id: 5, name: "Closing", icon: "🪢", short: "Close" },
    { id: 6, name: "Post-Op", icon: "🏥", short: "ICU" },
  ],
  totalTicks: 50,
},
{
  id: "aaa-repair",
  name: "AAA Repair",
  category: "advanced",
  specialty: "Vascular",
  description: "Open abdominal aortic aneurysm repair. Rupture and massive hemorrhage are existential threats.",
  patient: {
    name: "George P.", age: 72, sex: "Male", weight: "88 kg", bloodType: "O+",
    admission: "6.5cm infrarenal AAA with back pain, urgent repair indicated",
    mood: "Worried", comorbidities: ["hypertension", "diabetes", "copd"],
    baselineVitals: { spo2: 95, heart_rate: 88, bp_systolic: 170, bp_diastolic: 95, temperature: 37.0, respiratory_rate: 18 },
  },
  initialState: { vitals_override: { spo2: 95, heart_rate: 88, bp_systolic: 170, bp_diastolic: 95, respiratory_rate: 18 }, riskProfile: RISK_PROFILES.critical },
  complicationWeights: cw([["hemorrhage", 8], ["cardiac_arrhythmia", 4], ["hypoxia", 3], ["thrombosis", 3]]),
  allowedComplications: ["hemorrhage", "cardiac_arrhythmia", "hypoxia", "thrombosis"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL"],
  escalationCurve: buildEscalation(45, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Exposure", icon: "🔪", short: "Open" },
    { id: 3, name: "Clamping", icon: "🩸", short: "Clamp" },
    { id: 4, name: "Graft", icon: "⚕️", short: "Graft" },
    { id: 5, name: "Closing", icon: "🪡", short: "Close" },
    { id: 6, name: "Post-Op", icon: "🏥", short: "ICU" },
  ],
  totalTicks: 45,
},
{
  id: "radical-prostatectomy",
  name: "Radical Prostatectomy",
  category: "advanced",
  specialty: "Urology",
  description: "Radical retropubic prostatectomy for prostate cancer. Nerve-sparing and bleeding control critical.",
  patient: {
    name: "Frank D.", age: 61, sex: "Male", weight: "86 kg", bloodType: "A+",
    admission: "Gleason 7 prostate adenocarcinoma, PSA 8.2, nerve-sparing candidate",
    mood: "Anxious about function", comorbidities: ["hypertension"],
    baselineVitals: { spo2: 98, heart_rate: 76, bp_systolic: 140, bp_diastolic: 85, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: { bp_systolic: 140 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["hemorrhage", 5], ["nerve_injury", 4], ["infection", 2]]),
  allowedComplications: ["hemorrhage", "nerve_injury", "infection"],
  decisionArchetypes: ["SURGICAL_DECISION"],
  escalationCurve: buildEscalation(35, "moderate"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Exposure", icon: "🔪", short: "Open" },
    { id: 3, name: "Dissection", icon: "🔍", short: "Dissect" },
    { id: 4, name: "Prostatectomy", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Anastomosis", icon: "🪡", short: "Anastomosis" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 35,
},
{
  id: "esophagectomy",
  name: "Esophagectomy",
  category: "advanced",
  specialty: "Thoracic / Surgical Oncology",
  description: "Ivor Lewis esophagectomy for esophageal cancer. Anastomotic leak and respiratory failure are key risks.",
  patient: {
    name: "Richard B.", age: 63, sex: "Male", weight: "72 kg", bloodType: "O-",
    admission: "Distal esophageal adenocarcinoma, dysphagia, 15lb weight loss",
    mood: "Determined", comorbidities: ["copd"],
    baselineVitals: { spo2: 95, heart_rate: 80, bp_systolic: 128, bp_diastolic: 78, temperature: 37.0, respiratory_rate: 18 },
  },
  initialState: { vitals_override: { spo2: 95, respiratory_rate: 18 }, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["hypoxia", 5], ["infection", 5], ["hemorrhage", 3], ["cardiac_arrhythmia", 2]]),
  allowedComplications: ["hypoxia", "infection", "hemorrhage", "cardiac_arrhythmia"],
  decisionArchetypes: ["AIRWAY_STABILITY", "INFECTION_MANAGEMENT"],
  escalationCurve: buildEscalation(45, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Abdominal Phase", icon: "🔪", short: "Abdominal" },
    { id: 3, name: "Thoracic Phase", icon: "🫁", short: "Thoracic" },
    { id: 4, name: "Anastomosis", icon: "🪡", short: "Anastomosis" },
    { id: 5, name: "Closing", icon: "🪢", short: "Close" },
    { id: 6, name: "Post-Op", icon: "🏥", short: "ICU" },
  ],
  totalTicks: 45,
},
{
  id: "hepatic-lobectomy",
  name: "Hepatic Lobectomy",
  category: "advanced",
  specialty: "Hepatobiliary",
  description: "Right hepatic lobectomy for colorectal liver metastasis. Bleeding control is the primary challenge.",
  patient: {
    name: "Nancy W.", age: 59, sex: "Female", weight: "68 kg", bloodType: "B+",
    admission: "Solitary right lobe liver metastasis from treated colon cancer",
    mood: "Cautiously optimistic", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 78, bp_systolic: 122, bp_diastolic: 78, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.high },
  complicationWeights: cw([["hemorrhage", 7], ["cardiac_arrhythmia", 3], ["infection", 2], ["hypoxia", 2]]),
  allowedComplications: ["hemorrhage", "cardiac_arrhythmia", "infection", "hypoxia"],
  decisionArchetypes: ["HEMODYNAMIC_CONTROL"],
  escalationCurve: buildEscalation(40, "aggressive"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Exposure", icon: "🔪", short: "Open" },
    { id: 3, name: "Mobilization", icon: "🔍", short: "Mobilize" },
    { id: 4, name: "Resection", icon: "⚕️", short: "Resect" },
    { id: 5, name: "Hemostasis", icon: "🩸", short: "Hemostasis" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 40,
},
{
  id: "lumbar-microdiscectomy",
  name: "Lumbar Microdiscectomy",
  category: "advanced",
  specialty: "Neurosurgery",
  description: "Microsurgical discectomy for lumbar disc herniation. Nerve root protection and dural preservation.",
  patient: {
    name: "Karen S.", age: 42, sex: "Female", weight: "70 kg", bloodType: "A+",
    admission: "L5-S1 disc herniation with progressive radiculopathy, failed 6 weeks of conservative care",
    mood: "In pain", comorbidities: [],
    baselineVitals: { spo2: 98, heart_rate: 78, bp_systolic: 125, bp_diastolic: 80, temperature: 37.0, respiratory_rate: 16 },
  },
  initialState: { vitals_override: {}, riskProfile: RISK_PROFILES.moderate },
  complicationWeights: cw([["nerve_injury", 5], ["hemorrhage", 2], ["infection", 2]]),
  allowedComplications: ["nerve_injury", "hemorrhage", "infection"],
  decisionArchetypes: ["PAIN_MANAGEMENT"],
  escalationCurve: buildEscalation(30, "moderate"),
  phases: [
    { id: 1, name: "Pre-Op", icon: "🩺", short: "Pre-Op" },
    { id: 2, name: "Positioning", icon: "🛌", short: "Prone" },
    { id: 3, name: "Exposure", icon: "🔪", short: "Open" },
    { id: 4, name: "Discectomy", icon: "⚕️", short: "Procedure" },
    { id: 5, name: "Closing", icon: "🪡", short: "Close" },
    { id: 6, name: "Post-Op", icon: "📊", short: "Post-Op" },
  ],
  totalTicks: 30,
  },
  {
    id: "cabg-offpump",
    name: "Off-Pump CABG",
    category: "advanced",
    specialty: "Cardiovascular",
    description: "Beating-heart coronary artery bypass. Stabilize myocardium, perform anastomoses without cardiopulmonary bypass.",
    patient: {
      name: "James T.", age: 68, sex: "Male", weight: "82 kg", bloodType: "O-",
      admission: "Triple-vessel coronary disease, poor candidate for CPB due to severe COPD",
      mood: "Anxious", comorbidities: ["COPD", "hypertension", "diabetes"],
      baselineVitals: { spo2: 94, heart_rate: 90, bp_systolic: 155, bp_diastolic: 85, temperature: 37.0, respiratory_rate: 20 },
    },
    initialState: { vitals_override: { spo2: 94, heart_rate: 90, bp_systolic: 155 }, riskProfile: RISK_PROFILES.high },
    complicationWeights: cw([["cardiac_arrhythmia", 6], ["hemorrhage", 4], ["hypoxia", 5], ["thrombosis", 3]]),
    allowedComplications: ["cardiac_arrhythmia", "hemorrhage", "hypoxia", "thrombosis"],
    decisionArchetypes: ["HEMODYNAMIC_CONTROL", "AIRWAY_STABILITY"],
    escalationCurve: buildEscalation(45, "aggressive"),
    phases: [
      { id: 1, name: "Pre-Op Evaluation", icon: "🩺", short: "Pre-Op" },
      { id: 2, name: "Anesthesia & Induction", icon: "💉", short: "Induction" },
      { id: 3, name: "Sternotomy & Harvest", icon: "🔪", short: "Harvest" },
      { id: 4, name: "Stabilization & Exposure", icon: "🫀", short: "Stabilize" },
      { id: 5, name: "Distal Anastomoses", icon: "🪡", short: "Distal" },
      { id: 6, name: "Proximal Anastomoses", icon: "📈", short: "Proximal" },
      { id: 7, name: "Closure", icon: "🪢", short: "Close" },
      { id: 8, name: "ICU & Recovery", icon: "🏥", short: "ICU" },
    ],
    totalTicks: 45,
  },
];

// ════════════════════════════════════════════════════
//  REGISTRY ACCESS
// ════════════════════════════════════════════════════

export const PROCEDURE_REGISTRY: Record<string, ProcedureDefinition> = {};
for (const proc of ALL_30) {
  PROCEDURE_REGISTRY[proc.id] = proc;
}

export function getProcedure(id: string): ProcedureDefinition {
  return PROCEDURE_REGISTRY[id] ?? PROCEDURE_REGISTRY["appendectomy"];
}

export function listProcedures(): ProcedureDefinition[] {
  return ALL_30;
}

export function procedureExists(id: string): boolean {
  return id in PROCEDURE_REGISTRY;
}
